name: quadrant_server
description: Standalone Quadrant Todo backend server.
version: 1.7.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.5.0
  quadrant_api_server: ^1.0.0
  quadrant_application: ^1.0.0
  quadrant_store: ^1.0.0
  shelf: ^1.4.0

dev_dependencies:
  http: ^1.2.0
  test: ^1.25.0
